generic-booster:
  appName: simple-app

  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.14.2

  replicaCount: 1

  configMaps:
  - name: simple
    data:
      index.html: |
        <h1>Simple</h1>

  configMapMounts:
    - name: simple
      mountPath: /usr/share/nginx/html

  podAnnotations:
    fluentbit.io/exclude: "true"
    prometheus.io/scrape: "false"
